name: Build (main)
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Free Disk Space
        run: |
          df -hT
          sudo apt-get purge -y aspnetcore-* clang-* dotnet-* google-chrome-* llvm-* mono-* mysql-* php* r-*
          sudo apt-get autoremove
          sudo rm -rf /usr/local/.ghcup /usr/local/julia* /usr/local/lib/android
          df -hT
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          submodules: true
      - uses: docker/setup-buildx-action@v3.7.1
      - uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Parameters
        id: params
        env:
          REPOSITORY: ${{ github.repository }}
        run: |
          echo "repository_lower=${REPOSITORY@L}" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v6.9.0
        with:
          push: false
          cache-from: |
            type=registry,ref=ghcr.io/${{ steps.params.outputs.repository_lower }}/cache:main
          cache-to: |
            type=registry,mode=max,ref=ghcr.io/${{ steps.params.outputs.repository_lower }}/cache:main
          context: .
          outputs: type=local,dest=./build/
      - uses: actions/upload-artifact@v4.4.3
        with:
          path: build/*.bin
